version: "3.9"
services:
  devopsdb:
    image: varadya143aradya/automation:db
    deploy:
      replicas: 1
    networks:
      - mynetwork

  application:
    image: varadya143aradya/automation:app
    ports:
      - "1111:8080"
    deploy:
      replicas: 3
    networks:
      - mynetwork
    depends_on:
      - devopsdb

networks:
  mynetwork:
    driver: overlay
