version: "3.9"
services:
  devopsdb:
    image: varadya143aradya/automation:db
    ports:
     - "3306:3306"

  application:
    image: varadya143aradya/automation:app
    ports:
      - "1111:8080"
    depends_on:
      - devopsdb

