version: "3.9"

services:
  devopsdb:
    image: varadya143aradya/automation:db
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - mynetwork

  application:
    image: varadya143aradya/automation:app
    ports:
      - "1111:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://devopsdb:3306/accounts?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
    attachable: true
